services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: secretpassword
      MYSQL_USER: techrevolution
      MYSQL_PASSWORD: Welcome@123
    ports:
      - "3303:3306"
    volumes:
      - ./mysql:/var/lib/mysql