spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3303/inventory_service
    username: root
    password: secretpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8082