services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql
    ports:
      - "3303:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secretpassword
      MYSQL_USER: techrevolution
      MYSQL_PASSWORD: Welcome@123
    volumes:
      - ./mysql:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql